apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server
data:
  # property-like keys; each key maps to a simple value
  CONFIG_SERVER_URL: "http://config-server:8888"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=875f8dc8-53f8-441f-81dc-3fe6a3b04827;IngestionEndpoint=https://northeurope-2.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
